version:     "0001--10-Sep-2022"
copyright:   "2022"
author:      "Naufal Weise W."
title:       "OS222: Operating Systems 2022-2"
repourl:     "https://github.com/naufalweise/os222"
pageurl:     "https://github.io/naufalweise/os222"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
